apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kappnavs.kappnav.io
spec:
  group: kappnav.io
  names:
    kind: Kappnav
    listKind: KappnavList
    plural: kappnavs
    singular: kappnav
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            appNavAPI:
              properties:
                repository:
                  type: string
                resources:
                  properties:
                    enabled:
                      type: boolean
                    limits:
                      properties:
                        cpu:
                          type: string
                        memory:
                          type: string
                      type: object
                    requests:
                      properties:
                        cpu:
                          type: string
                        memory:
                          type: string
                      type: object
                  type: object
                tag:
                  type: string
              type: object
            appNavController:
              properties:
                repository:
                  type: string
                resources:
                  properties:
                    enabled:
                      type: boolean
                    limits:
                      properties:
                        cpu:
                          type: string
                        memory:
                          type: string
                      type: object
                    requests:
                      properties:
                        cpu:
                          type: string
                        memory:
                          type: string
                      type: object
                  type: object
                tag:
                  type: string
              type: object
            appNavUI:
              properties:
                repository:
                  type: string
                resources:
                  properties:
                    enabled:
                      type: boolean
                    limits:
                      properties:
                        cpu:
                          type: string
                        memory:
                          type: string
                      type: object
                    requests:
                      properties:
                        cpu:
                          type: string
                        memory:
                          type: string
                      type: object
                  type: object
                tag:
                  type: string
              type: object
            env:
              properties:
                kubeEnv:
                  type: string
              type: object
            extensionContainers:
              additionalProperties:
                properties:
                  repository:
                    type: string
                  resources:
                    properties:
                      enabled:
                        type: boolean
                      limits:
                        properties:
                          cpu:
                            type: string
                          memory:
                            type: string
                        type: object
                      requests:
                        properties:
                          cpu:
                            type: string
                          memory:
                            type: string
                        type: object
                    type: object
                  tag:
                    type: string
                type: object
              type: object
            image:
              properties:
                pullPolicy:
                  type: string
                pullSecrets:
                  items:
                    type: string
                  type: array
              type: object
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  lastTransitionTime:
                    format: date-time
                    type: string
                  lastUpdateTime:
                    format: date-time
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                type: object
              type: array
          type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
