apiVersion: kappnav.io/v1
kind: Kappnav
metadata:
  name: example-kappnav
spec:

  ###############################################################################
  ## kAppNav REST API variables
  ###############################################################################

  appNavAPI:
    repository: kappnav/apis
    tag: 0.1.0
    resources:
      enabled: false
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 512Mi

  ###############################################################################
  ## kAppNav Controller variables
  ###############################################################################

  appNavController:
    repository: kappnav/controller
    tag: 0.1.0
    resources:
      enabled: false
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 512Mi

  ###############################################################################
  ## kAppNav UI variables
  ###############################################################################

  appNavUI:
    repository: kappnav/ui
    tag: 0.1.0
    service:
      type: ClusterIP
    resources:
      enabled: false
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 512Mi


  ###############################################################################
  ## kAppNav Init Container variables
  ###############################################################################

  appNavInit:
    repository: kappnav/init
    tag: 0.1.0
    resources:
      enabled: false
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 512Mi

  image:
    pullPolicy: Always
    pullSecrets: []

  ###############################################################################
  ## Environmental variables
  ###############################################################################
  env:
    kubeEnv: okd

  ###############################################################################
  ## Architecture
  ###############################################################################
  # Specify architecture (amd64, ppc64le, s390x) and weight to be
  # used for scheduling as follows :
  #   0 - Do not use
  #   1 - Least preferred
  #   2 - No preference
  #   3 - Most preferred
  arch:
    amd64: "2 - No preference"
    ppc64le: "2 - No preference"
    s390x: "2 - No preference"

   ###############################################################################
  ## OpenShift web console variables
  ###############################################################################
  console:
    enableOkdFeaturedApp: true
    enableOkdLauncher: true