// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kappnav) DeepCopyInto(out *Kappnav) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kappnav.
func (in *Kappnav) DeepCopy() *Kappnav {
	if in == nil {
		return nil
	}
	out := new(Kappnav)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Kappnav) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KappnavContainerConfiguration) DeepCopyInto(out *KappnavContainerConfiguration) {
	*out = *in
	out.Resources = in.Resources
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KappnavContainerConfiguration.
func (in *KappnavContainerConfiguration) DeepCopy() *KappnavContainerConfiguration {
	if in == nil {
		return nil
	}
	out := new(KappnavContainerConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KappnavList) DeepCopyInto(out *KappnavList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Kappnav, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KappnavList.
func (in *KappnavList) DeepCopy() *KappnavList {
	if in == nil {
		return nil
	}
	out := new(KappnavList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KappnavList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KappnavResourceConstraints) DeepCopyInto(out *KappnavResourceConstraints) {
	*out = *in
	out.Requests = in.Requests
	out.Limits = in.Limits
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KappnavResourceConstraints.
func (in *KappnavResourceConstraints) DeepCopy() *KappnavResourceConstraints {
	if in == nil {
		return nil
	}
	out := new(KappnavResourceConstraints)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KappnavServiceContainerConfiguration) DeepCopyInto(out *KappnavServiceContainerConfiguration) {
	*out = *in
	out.KappnavContainerConfiguration = in.KappnavContainerConfiguration
	out.Service = in.Service
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KappnavServiceContainerConfiguration.
func (in *KappnavServiceContainerConfiguration) DeepCopy() *KappnavServiceContainerConfiguration {
	if in == nil {
		return nil
	}
	out := new(KappnavServiceContainerConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KappnavSpec) DeepCopyInto(out *KappnavSpec) {
	*out = *in
	if in.AppNavAPI != nil {
		in, out := &in.AppNavAPI, &out.AppNavAPI
		*out = new(KappnavContainerConfiguration)
		**out = **in
	}
	if in.AppNavController != nil {
		in, out := &in.AppNavController, &out.AppNavController
		*out = new(KappnavContainerConfiguration)
		**out = **in
	}
	if in.AppNavUI != nil {
		in, out := &in.AppNavUI, &out.AppNavUI
		*out = new(KappnavServiceContainerConfiguration)
		**out = **in
	}
	if in.AppNavInit != nil {
		in, out := &in.AppNavInit, &out.AppNavInit
		*out = new(KappnavContainerConfiguration)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KappnavSpec.
func (in *KappnavSpec) DeepCopy() *KappnavSpec {
	if in == nil {
		return nil
	}
	out := new(KappnavSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KappnavStatus) DeepCopyInto(out *KappnavStatus) {
	*out = *in
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
	if in.LastUpdateTime != nil {
		in, out := &in.LastUpdateTime, &out.LastUpdateTime
		*out = (*in).DeepCopy()
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KappnavStatus.
func (in *KappnavStatus) DeepCopy() *KappnavStatus {
	if in == nil {
		return nil
	}
	out := new(KappnavStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Resources) DeepCopyInto(out *Resources) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Resources.
func (in *Resources) DeepCopy() *Resources {
	if in == nil {
		return nil
	}
	out := new(Resources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Service) DeepCopyInto(out *Service) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Service.
func (in *Service) DeepCopy() *Service {
	if in == nil {
		return nil
	}
	out := new(Service)
	in.DeepCopyInto(out)
	return out
}
