###########################################################################
# Copyright 2019 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# imitations under the License.
###########################################################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: kappnav.actions.deployment
data:
  url-actions: |
    [
{{ if or (eq .Spec.Env.KubeEnv "minishift") (eq .Spec.Env.KubeEnv "okd") (eq .Spec.Env.KubeEnv "ocp") }}
      { 
        "name":"replicas", 
        "text":"View Replicas", 
        "text.nls":"action.url.deployment.replicas.text", 
        "description":"View Deployment replicas", 
        "description.nls":"action.url.deployment.replicas.desc", 
        # do not use / before project otherwise it will have // as openshift console url end with / already
        "url-pattern":"${builtin.openshift-console-url}project/${resource.$.metadata.namespace}/browse/deployment/${resource.$.metadata.name}", 
        "open-window": "current", 
        "menu-item": "true" 
      },
      { 
        "name":"detail", 
        "text":"View Detail", 
        "text.nls":"action.url.deployment.detail.text", 
        "description":"View Deployment detail", 
        "description.nls":"action.url.deployment.detail.desc", 
{{ if or (eq .Spec.Env.KubeEnv "okd") (eq .Spec.Env.KubeEnv "ocp")}}
        # do not use / before k8s otherwise it will have // as openshift console url end with / already
        "url-pattern":"${builtin.openshift-admin-console-url}k8s/ns/${resource.$.metadata.namespace}/deployments/${resource.$.metadata.name}",
{{ else }}
        "url-pattern": "",
{{ end }}
        "open-window": "current", 
        "menu-item": "false" 
      }
{{ end }}
        
{{ if eq .Spec.Env.KubeEnv "minikube" }}       
      { 
        "name":"detail", 
        "text":"View Detail", 
        "text.nls":"action.url.deployment.detail.text", 
        "description":"View Deployment detail", 
        "description.nls":"action.url.deployment.detail.desc", 
        "url-pattern":"${builtin.openshift-console-url}/deployment/${resource.$.metadata.namespace}/${resource.$.metadata.name}?namespace=${resource.$.metadata.namespace}",
        "open-window": "current", 
        "menu-item": "false" 
      }  
{{ end }}
    ]
