###########################################################################
# Copyright 2019 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# imitations under the License.
###########################################################################
apiVersion: v1
kind: ConfigMap
metadata: 
  name: kappnav.status-mapping.pod
data:
  algorithm: "function getStatus(status) {

      var statusJson = JSON.parse(status);
      var statusText = 'Problem';
      var statusFlyover = '';
      var nlsJSON= {};
      var phase = statusJson.phase;

      if (phase == 'Running') {
        statusText = 'Normal';
        statusFlyover = 'Status returned by platform: '+phase;
	      nlsJSON= [ 'status.flyover.pod', phase ]; 
      } else if (phase == 'Succeeded') {
        statusText = 'Normal';
        statusFlyover = 'Status returned by platform: '+phase;
	      nlsJSON= [ 'status.flyover.pod', phase ]; 
      } else if (phase == 'Pending') {
        statusText = 'Warning';
        statusFlyover = 'No status returned by platform';
        nlsJSON= [ 'status.flyover.pod.error' ]; 

	      if (statusJson.containerStatuses !== undefined) { 
	         if (statusJson.containerStatuses[0] !== undefined) { 
	            if (statusJson.containerStatuses[0].state !== undefined) { 
                 if (statusJson.containerStatuses[0].state.waiting !== undefined) { 
                    if (statusJson.containerStatuses[0].state.waiting.reason !== undefined) { 
                       statusFlyover = 'Status returned by platform: '+statusJson.containerStatuses[0].state.waiting.reason;
                       nlsJSON= [ 'status.flyover.pod', statusJson.containerStatuses[0].state.waiting.reason ]; 
		                }
	               }
	            }
           }
        }
      } else {
        statusText = 'Problem';
        statusFlyover = 'No status returned by platform';
	      nlsJSON= [ 'status.flyover.pod.error' ]; 
      }

      var statusJSON= { 'value': statusText, 'flyover': statusFlyover, 'flyover.nls': nlsJSON };

      return JSON.stringify(statusJSON);
}"    
